FROM python:3.6-alpine
RUN mkdir /opt/dagda
COPY dagda /opt/dagda
ADD requirements.txt /opt/dagda/requirements.txt
RUN pip install -r /opt/dagda/requirements.txt
WORKDIR /opt/dagda
ENTRYPOINT ["python", "dagdaragent.py"]
