FROM python:3.6-alpine

#===================
# Jenkins user
#===================
ARG user=dagda
ARG group=dagda
ARG uid=1000
ARG gid=1000
ENV DAGDA_HOME /opt/dagda
RUN addgroup -g ${gid} ${group} && \
    adduser -u ${uid-} -D -G ${group} -s /bin/bash ${user} && \
    mkdir -p $DAGDA_HOME && \
    chown $user:$group $DAGDA_HOME

#===================
# Python requirement
#===================
COPY dagda /opt/dagda
ADD requirements.txt /opt/dagda/requirements.txt
RUN pip install -r /opt/dagda/requirements.txt
WORKDIR /opt/dagda
USER dagda
ENTRYPOINT ["python", "dagdaragent.py"]
